server:
  port: 4001

spring:
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 10
  client:
    region: default
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true