FROM alpine-java:base

MAINTAINER inboxtrevorjohnson@gmail.com

RUN apk --no-cache add netcat-openbsd

COPY resources/LifeBioZuul-1.0-exec.jar /opt/spring-cloud/lib/
COPY resources/lifebio-zuul-entrypoint.sh /opt/spring-cloud/bin/

ENTRYPOINT ["/usr/bin/java"]

RUN chmod 755 /opt/spring-cloud/bin/lifebio-zuul-entrypoint.sh

EXPOSE 8084
