server:
  port: 8888

# Congig server settings
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inboxtrevorjohnson/lifebio
          basedir: LifeBioConfigServer/src/main/config/
