FROM alpine-java:base

MAINTAINER inboxtrevorjohnson@gmail.com

RUN apk --no-cache add netcat-openbsd

COPY resources/LifeBioContactDetails-1.0-exec.jar /opt/spring-cloud/lib/
COPY resources/lifebio-contact-details-entrypoint.sh /opt/spring-cloud/bin/

ENTRYPOINT ["/usr/bin/java"]

RUN chmod 755 /opt/spring-cloud/bin/lifebio-contact-details-entrypoint.sh

EXPOSE 4002
